travis:
  secure:
    BINSTAR_TOKEN: E1cYTPV/NXoov0U64ZHi0l3czEYMd35zTC2fYZKkDsaZ87QsjbQr5Te4vc/T1iHV8UGWbHt0BosV5Vdm6ykWS1gMOl8D7MyuXUmbiASHhUKgUXcLluuEJmgnZq65iuhKk4pvZRNANW7WIXtrxkihVEZbKue0O6bVrUr/9lEnKp7khEiT/aOBDBdJwI1YVvkLw5jss4V5vaMKsv3CXFLBV/znsad91zeHWmdOemOlIsJJoyFW+n3cOQtf3NvVgdk39eKN4GmH9PBkpE0IKXAzrVTH3SfoZ6A4s25AwLEotC6fsEzc8MmSwZB5youC24xK91qTxtBe1HYrt/sM1JOHXPWVOZTd8/9gHtJ3NtZ15dhGrXfyjto/LQgNG1EIznXHPxpxf3AQM2cZCT2dOtPdlEYVTU/1IBtqjLkWBptE3kqcvL6Mnyg6arXu2ts/1hZjpej/LRmgh8yFvQWJCdavqqY+R5gOHayVDXLGxdqlPNInNu5bKQ8rSHVJI/Ppb7Qr1YnVtEGhir73wijmI3vyOZM+mm7xaY6HTT2sYp9/n2n6NC6yZvAw9IOhsmZbteWz/V7WRwxc2t3ospUtZkymILLKokDOeVbLBvNVNRInLG7DMr9xagwSh4XuD/tW7M7KWB37HGtEsdG/ZqzDqZsioxKdmr6DYau0/bAcj8zb7Xs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
