travis:
  secure:
    BINSTAR_TOKEN: skl3GeWvSeBXxKh0FsrSO9t48Hrai9gY2Dx1gadlnNI08zAvGwjs9xOzrPLReA7Bho6mSxl/gXw66ewzhyo0BgW8c7KfKVA1NTi2Az23KMZ2ZC9dSG6QuV2nrT7SCqPXMobQFdyAPEDdaBU2JcxRNei62vVcIsL/hYiwC1aTTQu7AwytWfNRD21aCmSr+BuwyDD+PN3guKUqhsTmqQuf4XZ57GLRY275Piiz7kMExvpkZgtb7KX/HJ/FquyyNtIpzVZFavWrxyL5dCSQFzb+C4U10ATKHezxlU/QLOszyFiibV/8fxVoLntIP9Ks+68Dha6mCQDep0Y+O2UWFprHN2ItpEizV5FXAaaWZ1IuuClk8tpCP8vmyUtv4DjotDKV6QeLzCfRaFmZi7P0BBkhfCau7iSwFlblE2u+BtLpZb95Jb3mbObu5kQKn6Z89wzz2ku27ahjuwP/vR2E6sV9HmbOeJhB6kaaiDFyxFj43sG0LosEjwT6JLC1/zx8zFYBhJNQ41DPl0Huj+gfIIdN3VJ49cAXKMWzq+3KAhdTahgQFNgPKgkfKbD1YTVTdgm3zR4J0X84eY3/JsnRso5W8SGDiz/go9JSGE72HdHDJegUuIA0J+pWMZA1WuMJ/HFwVzj28HpO3gsM7i/HklFIczsntPJHa8WLVAaeU3CcHLU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
